# Project information
site_name: Pemrograman Berbasis Platform
site_url: https://experimental-pbp.github.io/website/
site_author: PBP Fasilkom UI
site_description: >-
  Situs web materi mata kuliah Pemrograman Berbasis Platform,
  Fakultas Ilmu Komputer, Universitas Indonesia

# Copyright
copyright: Copyright &copy; 2022 PBP Fasilkom UI

theme:
  logo: assets/img/makara.png
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
