# Project information
site_name: Experimental PBP
site_url: https://experimental-pbp.github.io/website/
site_author: PBP Fasilkom UI
site_description: >-
  Situs web materi Pemrograman Berbasis Platform,
  dikembangkan secara terpisah dan eksperimental.

# Copyright
copyright: Copyright &copy; 2022 Muhammad Athallah

theme:
  language: id
  logo: assets/img/logo.png
  favicon: assets/img/logo.png
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
