site_name: Pemrograman Berbasis Platform
theme:
  logo: assets/img/makara.png
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
